paths:
  chunks_csv: data/processed/chunks.csv
  index_dir: data/index

ir:
  chunk_size: 500
  chunk_overlap: 100
  top_k: 12
  alpha_bm25: 1.0   # 1.0=BM25-only; 0.0=Embeddings-only; 0.5=Hybrid

embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
  use_faiss: true
  faiss_nprobe: 8

qg:
  use_transformers: true
  model_name: t5-small
  max_new_tokens: 48
  num_beams: 4
  no_repeat_ngram_size: 3

nlp:
  spacy_model: en_core_web_sm
