ir:
  chunk_size: 500          # characters per chunk (approx)
  chunk_overlap: 50
  alpha_bm25: 0.5          # weight for BM25 vs embedding similarity
  top_k: 10
nlp:
  spacy_model: en_core_web_sm
qg:
  use_transformers: true   # if model fails to load, falls back to templates
  model_name: t5-small
app:
  index_dir: data/index
  processed_csv: data/processed/chunks.csv
